/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const BillId = IDL.Nat;
export const ApplyStoreCreditInput = IDL.Record({
  'customerPhone' : IDL.Text,
  'amount' : IDL.Float64,
  'billId' : BillId,
});
export const CreditTransactionId = IDL.Nat;
export const ReturnBillId = IDL.Nat;
export const Timestamp = IDL.Int;
export const CreditTransactionType = IDL.Variant({
  'Used' : IDL.Null,
  'Earned' : IDL.Null,
});
export const CreditTransaction = IDL.Record({
  'id' : CreditTransactionId,
  'returnBillId' : IDL.Opt(ReturnBillId),
  'date' : Timestamp,
  'note' : IDL.Text,
  'txType' : CreditTransactionType,
  'amount' : IDL.Float64,
  'billId' : IDL.Opt(BillId),
});
export const CustomerCredit = IDL.Record({
  'balance' : IDL.Float64,
  'shopId' : IDL.Text,
  'customerId' : IDL.Text,
  'transactions' : IDL.Vec(CreditTransaction),
});
export const ReturnStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const ReturnItem = IDL.Record({
  'returnQty' : IDL.Float64,
  'originalRate' : IDL.Float64,
  'name' : IDL.Text,
  'lineTotal' : IDL.Float64,
  'productId' : ProductId,
  'reason' : IDL.Opt(IDL.Text),
});
export const ReturnBill = IDL.Record({
  'id' : ReturnBillId,
  'customerName' : IDL.Text,
  'status' : ReturnStatus,
  'originalBillId' : BillId,
  'shopId' : IDL.Text,
  'customerPhone' : IDL.Text,
  'totalRefundAmount' : IDL.Float64,
  'approvedAt' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'returnItems' : IDL.Vec(ReturnItem),
});
export const PaymentType = IDL.Variant({
  'full' : IDL.Null,
  'partial' : IDL.Null,
});
export const ExtraCharge = IDL.Record({
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const BillItem = IDL.Record({
  'qty' : IDL.Float64,
  'name' : IDL.Text,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'lineTotal' : IDL.Float64,
  'productId' : ProductId,
  'taxAmt' : IDL.Float64,
  'discount' : IDL.Float64,
});
export const PriceType = IDL.Variant({
  'Retail' : IDL.Null,
  'Custom' : IDL.Null,
  'Wholesale' : IDL.Null,
});
export const CreateBillInput = IDL.Record({
  'customerName' : IDL.Text,
  'shopId' : IDL.Text,
  'customerPhone' : IDL.Text,
  'amountPaid' : IDL.Float64,
  'billDiscount' : IDL.Float64,
  'paymentType' : PaymentType,
  'extraCharges' : IDL.Vec(ExtraCharge),
  'items' : IDL.Vec(BillItem),
  'priceType' : PriceType,
  'staffCreatedBy' : IDL.Opt(IDL.Principal),
});
export const BillStatus = IDL.Variant({
  'Saved' : IDL.Null,
  'Draft' : IDL.Null,
  'Cancelled' : IDL.Null,
});
export const TaxBreakdown = IDL.Record({
  'cgst' : IDL.Float64,
  'igst' : IDL.Float64,
  'sgst' : IDL.Float64,
});
export const TaxSystem = IDL.Variant({
  'GST' : IDL.Null,
  'VAT' : IDL.Null,
  'Generic' : IDL.Null,
  'SalesTax' : IDL.Null,
});
export const Bill = IDL.Record({
  'id' : BillId,
  'customerName' : IDL.Text,
  'status' : BillStatus,
  'shopId' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : Timestamp,
  'shareToken' : IDL.Opt(IDL.Text),
  'amountPaid' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'billNumber' : IDL.Nat,
  'taxBreakdown' : TaxBreakdown,
  'paymentType' : PaymentType,
  'extraCharges' : IDL.Vec(ExtraCharge),
  'profit' : IDL.Float64,
  'amountPending' : IDL.Float64,
  'items' : IDL.Vec(BillItem),
  'priceType' : PriceType,
  'staffCreatedBy' : IDL.Opt(IDL.Principal),
  'totalDiscount' : IDL.Float64,
  'lastReminderSent' : IDL.Opt(Timestamp),
  'taxSystem' : TaxSystem,
  'taxRate' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const CustomerId = IDL.Nat;
export const ShopType = IDL.Variant({
  'Salon' : IDL.Null,
  'Footwear' : IDL.Null,
  'Jewelry' : IDL.Null,
  'AutoParts' : IDL.Null,
  'Grocery' : IDL.Null,
  'AgroProducts' : IDL.Null,
  'Hardware' : IDL.Null,
  'General' : IDL.Null,
  'BuildingMaterial' : IDL.Null,
  'Stationery' : IDL.Null,
  'Medical' : IDL.Null,
  'Electrical' : IDL.Null,
  'Restaurant' : IDL.Null,
  'FruitsVegetables' : IDL.Null,
  'Electronics' : IDL.Null,
  'Mobile' : IDL.Null,
  'Clothing' : IDL.Null,
});
export const SalonFields = IDL.Record({
  'duration' : IDL.Nat,
  'staffName' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
});
export const SizeSystem = IDL.Variant({
  'EU' : IDL.Null,
  'UK' : IDL.Null,
  'US' : IDL.Null,
});
export const FootwearFields = IDL.Record({
  'model' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'color' : IDL.Text,
  'size' : IDL.Text,
  'sizeSystem' : SizeSystem,
  'brand' : IDL.Text,
});
export const Metal = IDL.Variant({
  'Gold' : IDL.Null,
  'Platinum' : IDL.Null,
  'Other' : IDL.Null,
  'Silver' : IDL.Null,
});
export const JewelryFields = IDL.Record({
  'metal' : Metal,
  'expiryDate' : IDL.Opt(IDL.Text),
  'metalRate' : IDL.Float64,
  'purity' : IDL.Text,
  'makingCharges' : IDL.Float64,
  'weightGrams' : IDL.Float64,
});
export const AutoPartsFields = IDL.Record({
  'vehicleBrand' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'partName' : IDL.Text,
  'vehicleModel' : IDL.Text,
  'partNo' : IDL.Text,
});
export const GroceryFields = IDL.Record({
  'expiryDate' : IDL.Opt(IDL.Text),
  'decimalQtyEnabled' : IDL.Bool,
});
export const AgroProductsFields = IDL.Record({
  'weight' : IDL.Float64,
  'expiryDate' : IDL.Opt(IDL.Text),
  'weightUnit' : IDL.Text,
  'productType' : IDL.Text,
  'batchNumber' : IDL.Opt(IDL.Text),
  'brand' : IDL.Text,
  'cropType' : IDL.Text,
});
export const HardwareFields = IDL.Record({
  'sku' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
});
export const GeneralFields = IDL.Record({ 'expiryDate' : IDL.Opt(IDL.Text) });
export const BuildingMaterialFields = IDL.Record({
  'weight' : IDL.Text,
  'material_type' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'color' : IDL.Text,
  'grade' : IDL.Text,
  'size_dimensions' : IDL.Text,
  'brand' : IDL.Text,
});
export const StationerySubType = IDL.Variant({
  'Pen' : IDL.Null,
  'Book' : IDL.Null,
  'File' : IDL.Null,
  'Notebook' : IDL.Null,
  'Other' : IDL.Null,
});
export const StationeryFields = IDL.Record({
  'bookSubject' : IDL.Text,
  'subType' : StationerySubType,
  'bookClass' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'penColor' : IDL.Text,
  'notebookPages' : IDL.Nat,
  'bookMedium' : IDL.Text,
  'notebookSize' : IDL.Text,
  'penBrand' : IDL.Text,
});
export const PackType = IDL.Variant({
  'Strip' : IDL.Null,
  'Bottle' : IDL.Null,
  'Tablet' : IDL.Null,
  'Other' : IDL.Null,
});
export const MedicalFields = IDL.Record({
  'packType' : PackType,
  'expiryDate' : IDL.Text,
  'company' : IDL.Text,
  'batchNo' : IDL.Text,
  'composition' : IDL.Text,
  'isControlled' : IDL.Bool,
});
export const ElectricalFields = IDL.Record({
  'model' : IDL.Text,
  'isiCertified' : IDL.Bool,
  'lengthUnit' : IDL.Text,
  'wattage' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'color' : IDL.Text,
  'voltageRating' : IDL.Text,
  'wireGauge' : IDL.Text,
  'itemCategory' : IDL.Text,
  'batchNumber' : IDL.Text,
  'brand' : IDL.Text,
  'ampereRating' : IDL.Text,
});
export const RestaurantCategory = IDL.Variant({
  'Veg' : IDL.Null,
  'NonVeg' : IDL.Null,
  'Vegan' : IDL.Null,
});
export const RestaurantFields = IDL.Record({
  'expiryDate' : IDL.Opt(IDL.Text),
  'category' : RestaurantCategory,
});
export const FruitsVegetablesFields = IDL.Record({
  'unit' : IDL.Text,
  'freshnessDate' : IDL.Opt(IDL.Text),
  'originSource' : IDL.Text,
  'productType' : IDL.Text,
  'seasonalTag' : IDL.Text,
  'batchNumber' : IDL.Opt(IDL.Text),
  'variety' : IDL.Text,
});
export const ElectronicsFields = IDL.Record({
  'model' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'serialNo' : IDL.Text,
  'warrantyMonths' : IDL.Nat,
  'brand' : IDL.Text,
});
export const MobileFields = IDL.Record({
  'ram' : IDL.Text,
  'mobileCategory' : IDL.Text,
  'model' : IDL.Text,
  'displaySize' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'storage' : IDL.Text,
  'imei' : IDL.Text,
  'color' : IDL.Text,
  'compatibility' : IDL.Text,
  'accessoryType' : IDL.Text,
  'serialNumber' : IDL.Text,
  'warrantyMonths' : IDL.Nat,
  'brand' : IDL.Text,
  'processor' : IDL.Text,
});
export const ClothingFields = IDL.Record({
  'expiryDate' : IDL.Opt(IDL.Text),
  'color' : IDL.Text,
  'size' : IDL.Text,
  'itemName' : IDL.Text,
  'brand' : IDL.Text,
});
export const EngineFields = IDL.Variant({
  'Salon' : SalonFields,
  'Footwear' : FootwearFields,
  'Jewelry' : JewelryFields,
  'AutoParts' : AutoPartsFields,
  'Grocery' : GroceryFields,
  'AgroProducts' : AgroProductsFields,
  'Hardware' : HardwareFields,
  'General' : GeneralFields,
  'BuildingMaterial' : BuildingMaterialFields,
  'Stationery' : StationeryFields,
  'Medical' : MedicalFields,
  'Electrical' : ElectricalFields,
  'Restaurant' : RestaurantFields,
  'FruitsVegetables' : FruitsVegetablesFields,
  'Electronics' : ElectronicsFields,
  'Mobile' : MobileFields,
  'Clothing' : ClothingFields,
});
export const CreateProductInput = IDL.Record({
  'retailPrice' : IDL.Float64,
  'shopId' : IDL.Text,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Float64,
  'unit' : IDL.Text,
  'isActive' : IDL.Bool,
  'minStock' : IDL.Float64,
  'stock' : IDL.Float64,
  'labourCost' : IDL.Opt(IDL.Float64),
  'barcode' : IDL.Opt(IDL.Text),
  'shopType' : ShopType,
  'category' : IDL.Text,
  'transportCost' : IDL.Opt(IDL.Float64),
  'costPrice' : IDL.Float64,
  'engineFields' : EngineFields,
});
export const ProductView = IDL.Record({
  'id' : ProductId,
  'retailPrice' : IDL.Float64,
  'shopId' : IDL.Text,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Float64,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'lastSaleTime' : IDL.Opt(Timestamp),
  'isActive' : IDL.Bool,
  'minStock' : IDL.Float64,
  'updatedAt' : Timestamp,
  'stock' : IDL.Float64,
  'labourCost' : IDL.Opt(IDL.Float64),
  'barcode' : IDL.Opt(IDL.Text),
  'shopType' : ShopType,
  'category' : IDL.Text,
  'transportCost' : IDL.Opt(IDL.Float64),
  'costPrice' : IDL.Float64,
  'engineFields' : EngineFields,
});
export const CreateReturnInput = IDL.Record({
  'customerName' : IDL.Text,
  'originalBillId' : BillId,
  'customerPhone' : IDL.Text,
  'returnItems' : IDL.Vec(ReturnItem),
});
export const SupplierId = IDL.Text;
export const Supplier = IDL.Record({
  'id' : SupplierId,
  'shopId' : IDL.Text,
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'businessType' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'defaultTransportCharge' : IDL.Opt(IDL.Text),
});
export const SupplierPurchaseId = IDL.Text;
export const SupplierPurchase = IDL.Record({
  'id' : SupplierPurchaseId,
  'purchasePrice' : IDL.Text,
  'shopId' : IDL.Text,
  'purchaseDate' : IDL.Int,
  'productId' : IDL.Nat,
  'transportCharge' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'supplierId' : SupplierId,
});
export const AdminNoteView = IDL.Record({
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'noteId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'targetPrincipal' : IDL.Text,
  'updatedAt' : IDL.Opt(IDL.Int),
});
export const ShopAdminView = IDL.Record({
  'principal' : IDL.Text,
  'language' : IDL.Text,
  'currency' : IDL.Text,
  'shopName' : IDL.Text,
  'shopType' : IDL.Text,
  'taxSystem' : IDL.Text,
  'isDisabled' : IDL.Bool,
});
export const UserView = IDL.Record({
  'firstSeen' : IDL.Int,
  'principal' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'isActive' : IDL.Bool,
  'loginCount' : IDL.Nat,
  'shopName' : IDL.Text,
  'shopType' : IDL.Text,
  'lastSeen' : IDL.Int,
});
export const DeadStockProduct = IDL.Record({
  'name' : IDL.Text,
  'lastSaleTime' : IDL.Opt(Timestamp),
  'productId' : ProductId,
  'daysInactive' : IDL.Nat,
});
export const SmartDefaultCharges = IDL.Record({
  'defaultOtherCharge' : IDL.Opt(IDL.Text),
  'defaultLabourCharge' : IDL.Opt(IDL.Text),
  'defaultTransportCharge' : IDL.Opt(IDL.Text),
});
export const SupplierPurchaseWithName = IDL.Record({
  'supplierName' : IDL.Text,
  'purchase' : SupplierPurchase,
});
export const LowStockProduct = IDL.Record({
  'name' : IDL.Text,
  'productId' : ProductId,
  'minStock' : IDL.Float64,
  'stock' : IDL.Float64,
});
export const MetalRates = IDL.Record({
  'isStale' : IDL.Bool,
  'lastUpdated' : IDL.Int,
  'available' : IDL.Bool,
  'gold22k' : IDL.Float64,
  'gold24k' : IDL.Float64,
  'silver' : IDL.Float64,
});
export const ShopRole = IDL.Variant({ 'owner' : IDL.Null, 'staff' : IDL.Null });
export const NearExpiryProduct = IDL.Record({
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'productId' : ProductId,
  'daysLeft' : IDL.Int,
});
export const PublicBillView = IDL.Record({
  'id' : BillId,
  'customerName' : IDL.Text,
  'status' : BillStatus,
  'customerPhone' : IDL.Text,
  'createdAt' : Timestamp,
  'grandTotal' : IDL.Float64,
  'billNumber' : IDL.Nat,
  'taxBreakdown' : TaxBreakdown,
  'extraCharges' : IDL.Vec(ExtraCharge),
  'items' : IDL.Vec(BillItem),
  'priceType' : PriceType,
  'totalDiscount' : IDL.Float64,
  'taxSystem' : TaxSystem,
  'taxRate' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const AnalyticsPeriod = IDL.Variant({
  'Week' : IDL.Null,
  'Month' : IDL.Null,
  'Today' : IDL.Null,
});
export const SalesSummary = IDL.Record({
  'totalProfit' : IDL.Float64,
  'totalSales' : IDL.Float64,
  'billCount' : IDL.Nat,
});
export const NumberFormat = IDL.Variant({
  'Indian' : IDL.Null,
  'International' : IDL.Null,
});
export const Language = IDL.Variant({
  'BahasaIndonesia' : IDL.Null,
  'Swahili' : IDL.Null,
  'Urdu' : IDL.Null,
  'Portuguese' : IDL.Null,
  'Spanish' : IDL.Null,
  'Bengali' : IDL.Null,
  'Hindi' : IDL.Null,
  'English' : IDL.Null,
  'Arabic' : IDL.Null,
  'French' : IDL.Null,
});
export const DateFormat = IDL.Variant({
  'MMDDYYYY' : IDL.Null,
  'DDMMYYYY' : IDL.Null,
});
export const ShopConfig = IDL.Record({
  'isSetupComplete' : IDL.Bool,
  'numberFormat' : NumberFormat,
  'country' : IDL.Text,
  'shopPhone' : IDL.Text,
  'expiryAlertThresholdDays' : IDL.Nat,
  'minStockAlertEnabled' : IDL.Bool,
  'language' : Language,
  'dateFormat' : DateFormat,
  'vatNumber' : IDL.Opt(IDL.Text),
  'deadStockAlertDays' : IDL.Nat,
  'currency' : IDL.Text,
  'shopName' : IDL.Text,
  'shopType' : ShopType,
  'shopEmail' : IDL.Text,
  'taxSystem' : TaxSystem,
  'shopAddress' : IDL.Text,
  'taxRate' : IDL.Float64,
  'gstinNumber' : IDL.Opt(IDL.Text),
  'defaultCharges' : IDL.Opt(SmartDefaultCharges),
});
export const CustomerView = IDL.Record({
  'id' : CustomerId,
  'shopId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastPurchaseDate' : IDL.Opt(IDL.Int),
  'totalSpent' : IDL.Float64,
  'totalBills' : IDL.Nat,
  'phone' : IDL.Text,
});
export const StaffMember = IDL.Record({
  'principal' : IDL.Principal,
  'role' : ShopRole,
  'addedAt' : IDL.Int,
});
export const TopProduct = IDL.Record({
  'revenue' : IDL.Float64,
  'name' : IDL.Text,
  'productId' : ProductId,
  'totalQty' : IDL.Float64,
  'profit' : IDL.Float64,
});
export const BillFilter = IDL.Record({
  'status' : IDL.Opt(BillStatus),
  'shopId' : IDL.Opt(IDL.Text),
  'searchCustomer' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
});
export const ProductFilter = IDL.Record({
  'shopId' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'searchName' : IDL.Opt(IDL.Text),
  'shopType' : IDL.Opt(ShopType),
  'category' : IDL.Opt(IDL.Text),
});
export const ReturnFilter = IDL.Record({
  'status' : IDL.Opt(ReturnStatus),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
});
export const RejectReturnInput = IDL.Record({
  'returnBillId' : ReturnBillId,
  'reason' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateProductInput = IDL.Record({
  'id' : ProductId,
  'retailPrice' : IDL.Float64,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Float64,
  'unit' : IDL.Text,
  'isActive' : IDL.Bool,
  'minStock' : IDL.Float64,
  'stock' : IDL.Float64,
  'labourCost' : IDL.Opt(IDL.Float64),
  'barcode' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'transportCost' : IDL.Opt(IDL.Float64),
  'costPrice' : IDL.Float64,
  'engineFields' : EngineFields,
});

export const idlService = IDL.Service({
  'addAdminNote' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addStaff' : IDL.Func([IDL.Text, IDL.Principal], [Result], []),
  'adminBlockUser' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteShop' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'applyStoreCredit' : IDL.Func(
      [IDL.Text, ApplyStoreCreditInput],
      [CustomerCredit],
      [],
    ),
  'approveReturn' : IDL.Func([IDL.Text, ReturnBillId], [ReturnBill], []),
  'cancelBill' : IDL.Func([BillId], [IDL.Bool], []),
  'createBill' : IDL.Func([IDL.Text, CreateBillInput], [Bill], []),
  'createOrUpdateCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [CustomerId],
      [],
    ),
  'createProduct' : IDL.Func([CreateProductInput], [ProductView], []),
  'createReturn' : IDL.Func([IDL.Text, CreateReturnInput], [ReturnBill], []),
  'createSupplier' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Supplier],
      [],
    ),
  'createSupplierPurchase' : IDL.Func(
      [
        IDL.Text,
        SupplierId,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [SupplierPurchase],
      [],
    ),
  'deleteAdminNote' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
  'generateBillShareToken' : IDL.Func([BillId], [IDL.Opt(IDL.Text)], []),
  'getAdminNotes' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(AdminNoteView), 'err' : IDL.Text })],
      [],
    ),
  'getAllShops' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ShopAdminView), 'err' : IDL.Text })],
      [],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(UserView), 'err' : IDL.Text })],
      [],
    ),
  'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
  'getCustomerBills' : IDL.Func(
      [IDL.Text, CustomerId],
      [IDL.Vec(Bill)],
      ['query'],
    ),
  'getCustomerCredit' : IDL.Func([IDL.Text, IDL.Text], [CustomerCredit], []),
  'getDeadStockProducts' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(DeadStockProduct)],
      ['query'],
    ),
  'getDefaultCharges' : IDL.Func([], [IDL.Opt(SmartDefaultCharges)], ['query']),
  'getLastNPurchasesForProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(SupplierPurchaseWithName)],
      ['query'],
    ),
  'getLowStockProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LowStockProduct)],
      ['query'],
    ),
  'getMetalRates' : IDL.Func([], [MetalRates], ['query']),
  'getMyRole' : IDL.Func([IDL.Text], [ShopRole], []),
  'getNearExpiryProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NearExpiryProduct)],
      ['query'],
    ),
  'getNearExpiryProductsByDays' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(NearExpiryProduct)],
      ['query'],
    ),
  'getPendingPaymentBills' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], []),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductView)], ['query']),
  'getProductByBarcode' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ProductView)],
      ['query'],
    ),
  'getPublicBill' : IDL.Func(
      [BillId, IDL.Text],
      [IDL.Opt(PublicBillView)],
      ['query'],
    ),
  'getReturnsByBill' : IDL.Func([IDL.Text, BillId], [IDL.Vec(ReturnBill)], []),
  'getSalesSummary' : IDL.Func([IDL.Text, AnalyticsPeriod], [SalesSummary], []),
  'getShopConfig' : IDL.Func([], [IDL.Opt(ShopConfig)], ['query']),
  'getShopCustomers' : IDL.Func([IDL.Text], [IDL.Vec(CustomerView)], ['query']),
  'getShopStaff' : IDL.Func([IDL.Text], [IDL.Vec(StaffMember)], []),
  'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
  'getTopProducts' : IDL.Func(
      [IDL.Text, AnalyticsPeriod, IDL.Nat],
      [IDL.Vec(TopProduct)],
      [],
    ),
  'getUserDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserView, 'err' : IDL.Text })],
      [],
    ),
  'initAdmin' : IDL.Func([], [IDL.Bool], []),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'isSetupComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'listBills' : IDL.Func([IDL.Text, BillFilter], [IDL.Vec(Bill)], []),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(ProductView)], ['query']),
  'listPurchasesByProduct' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(SupplierPurchase)],
      ['query'],
    ),
  'listPurchasesBySupplier' : IDL.Func(
      [IDL.Text, SupplierId],
      [IDL.Vec(SupplierPurchase)],
      ['query'],
    ),
  'listReturns' : IDL.Func([IDL.Text, ReturnFilter], [IDL.Vec(ReturnBill)], []),
  'listSuppliersByShop' : IDL.Func([IDL.Text], [IDL.Vec(Supplier)], ['query']),
  'recordPayment' : IDL.Func([IDL.Text, BillId, IDL.Float64], [Bill], []),
  'recordReminderSent' : IDL.Func([IDL.Text, BillId], [], []),
  'recordUserLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'refreshMetalRates' : IDL.Func([], [], []),
  'rejectReturn' : IDL.Func([IDL.Text, RejectReturnInput], [ReturnBill], []),
  'removeStaff' : IDL.Func([IDL.Text, IDL.Principal], [Result], []),
  'saveShopConfig' : IDL.Func([ShopConfig], [ShopConfig], []),
  'searchCustomers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CustomerView)],
      ['query'],
    ),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'setDefaultCharges' : IDL.Func(
      [SmartDefaultCharges],
      [IDL.Opt(ShopConfig)],
      [],
    ),
  'setMetalRatesManual' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'setShopDisabled' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transformRatesResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProduct' : IDL.Func([UpdateProductInput], [IDL.Opt(ProductView)], []),
  'updateShopConfig' : IDL.Func([ShopConfig], [IDL.Opt(ShopConfig)], []),
  'updateSupplier' : IDL.Func(
      [
        SupplierId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Opt(Supplier)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const BillId = IDL.Nat;
  const ApplyStoreCreditInput = IDL.Record({
    'customerPhone' : IDL.Text,
    'amount' : IDL.Float64,
    'billId' : BillId,
  });
  const CreditTransactionId = IDL.Nat;
  const ReturnBillId = IDL.Nat;
  const Timestamp = IDL.Int;
  const CreditTransactionType = IDL.Variant({
    'Used' : IDL.Null,
    'Earned' : IDL.Null,
  });
  const CreditTransaction = IDL.Record({
    'id' : CreditTransactionId,
    'returnBillId' : IDL.Opt(ReturnBillId),
    'date' : Timestamp,
    'note' : IDL.Text,
    'txType' : CreditTransactionType,
    'amount' : IDL.Float64,
    'billId' : IDL.Opt(BillId),
  });
  const CustomerCredit = IDL.Record({
    'balance' : IDL.Float64,
    'shopId' : IDL.Text,
    'customerId' : IDL.Text,
    'transactions' : IDL.Vec(CreditTransaction),
  });
  const ReturnStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const ReturnItem = IDL.Record({
    'returnQty' : IDL.Float64,
    'originalRate' : IDL.Float64,
    'name' : IDL.Text,
    'lineTotal' : IDL.Float64,
    'productId' : ProductId,
    'reason' : IDL.Opt(IDL.Text),
  });
  const ReturnBill = IDL.Record({
    'id' : ReturnBillId,
    'customerName' : IDL.Text,
    'status' : ReturnStatus,
    'originalBillId' : BillId,
    'shopId' : IDL.Text,
    'customerPhone' : IDL.Text,
    'totalRefundAmount' : IDL.Float64,
    'approvedAt' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'returnItems' : IDL.Vec(ReturnItem),
  });
  const PaymentType = IDL.Variant({ 'full' : IDL.Null, 'partial' : IDL.Null });
  const ExtraCharge = IDL.Record({
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const BillItem = IDL.Record({
    'qty' : IDL.Float64,
    'name' : IDL.Text,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'lineTotal' : IDL.Float64,
    'productId' : ProductId,
    'taxAmt' : IDL.Float64,
    'discount' : IDL.Float64,
  });
  const PriceType = IDL.Variant({
    'Retail' : IDL.Null,
    'Custom' : IDL.Null,
    'Wholesale' : IDL.Null,
  });
  const CreateBillInput = IDL.Record({
    'customerName' : IDL.Text,
    'shopId' : IDL.Text,
    'customerPhone' : IDL.Text,
    'amountPaid' : IDL.Float64,
    'billDiscount' : IDL.Float64,
    'paymentType' : PaymentType,
    'extraCharges' : IDL.Vec(ExtraCharge),
    'items' : IDL.Vec(BillItem),
    'priceType' : PriceType,
    'staffCreatedBy' : IDL.Opt(IDL.Principal),
  });
  const BillStatus = IDL.Variant({
    'Saved' : IDL.Null,
    'Draft' : IDL.Null,
    'Cancelled' : IDL.Null,
  });
  const TaxBreakdown = IDL.Record({
    'cgst' : IDL.Float64,
    'igst' : IDL.Float64,
    'sgst' : IDL.Float64,
  });
  const TaxSystem = IDL.Variant({
    'GST' : IDL.Null,
    'VAT' : IDL.Null,
    'Generic' : IDL.Null,
    'SalesTax' : IDL.Null,
  });
  const Bill = IDL.Record({
    'id' : BillId,
    'customerName' : IDL.Text,
    'status' : BillStatus,
    'shopId' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : Timestamp,
    'shareToken' : IDL.Opt(IDL.Text),
    'amountPaid' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'billNumber' : IDL.Nat,
    'taxBreakdown' : TaxBreakdown,
    'paymentType' : PaymentType,
    'extraCharges' : IDL.Vec(ExtraCharge),
    'profit' : IDL.Float64,
    'amountPending' : IDL.Float64,
    'items' : IDL.Vec(BillItem),
    'priceType' : PriceType,
    'staffCreatedBy' : IDL.Opt(IDL.Principal),
    'totalDiscount' : IDL.Float64,
    'lastReminderSent' : IDL.Opt(Timestamp),
    'taxSystem' : TaxSystem,
    'taxRate' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const CustomerId = IDL.Nat;
  const ShopType = IDL.Variant({
    'Salon' : IDL.Null,
    'Footwear' : IDL.Null,
    'Jewelry' : IDL.Null,
    'AutoParts' : IDL.Null,
    'Grocery' : IDL.Null,
    'AgroProducts' : IDL.Null,
    'Hardware' : IDL.Null,
    'General' : IDL.Null,
    'BuildingMaterial' : IDL.Null,
    'Stationery' : IDL.Null,
    'Medical' : IDL.Null,
    'Electrical' : IDL.Null,
    'Restaurant' : IDL.Null,
    'FruitsVegetables' : IDL.Null,
    'Electronics' : IDL.Null,
    'Mobile' : IDL.Null,
    'Clothing' : IDL.Null,
  });
  const SalonFields = IDL.Record({
    'duration' : IDL.Nat,
    'staffName' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
  });
  const SizeSystem = IDL.Variant({
    'EU' : IDL.Null,
    'UK' : IDL.Null,
    'US' : IDL.Null,
  });
  const FootwearFields = IDL.Record({
    'model' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'color' : IDL.Text,
    'size' : IDL.Text,
    'sizeSystem' : SizeSystem,
    'brand' : IDL.Text,
  });
  const Metal = IDL.Variant({
    'Gold' : IDL.Null,
    'Platinum' : IDL.Null,
    'Other' : IDL.Null,
    'Silver' : IDL.Null,
  });
  const JewelryFields = IDL.Record({
    'metal' : Metal,
    'expiryDate' : IDL.Opt(IDL.Text),
    'metalRate' : IDL.Float64,
    'purity' : IDL.Text,
    'makingCharges' : IDL.Float64,
    'weightGrams' : IDL.Float64,
  });
  const AutoPartsFields = IDL.Record({
    'vehicleBrand' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'partName' : IDL.Text,
    'vehicleModel' : IDL.Text,
    'partNo' : IDL.Text,
  });
  const GroceryFields = IDL.Record({
    'expiryDate' : IDL.Opt(IDL.Text),
    'decimalQtyEnabled' : IDL.Bool,
  });
  const AgroProductsFields = IDL.Record({
    'weight' : IDL.Float64,
    'expiryDate' : IDL.Opt(IDL.Text),
    'weightUnit' : IDL.Text,
    'productType' : IDL.Text,
    'batchNumber' : IDL.Opt(IDL.Text),
    'brand' : IDL.Text,
    'cropType' : IDL.Text,
  });
  const HardwareFields = IDL.Record({
    'sku' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
  });
  const GeneralFields = IDL.Record({ 'expiryDate' : IDL.Opt(IDL.Text) });
  const BuildingMaterialFields = IDL.Record({
    'weight' : IDL.Text,
    'material_type' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'color' : IDL.Text,
    'grade' : IDL.Text,
    'size_dimensions' : IDL.Text,
    'brand' : IDL.Text,
  });
  const StationerySubType = IDL.Variant({
    'Pen' : IDL.Null,
    'Book' : IDL.Null,
    'File' : IDL.Null,
    'Notebook' : IDL.Null,
    'Other' : IDL.Null,
  });
  const StationeryFields = IDL.Record({
    'bookSubject' : IDL.Text,
    'subType' : StationerySubType,
    'bookClass' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'penColor' : IDL.Text,
    'notebookPages' : IDL.Nat,
    'bookMedium' : IDL.Text,
    'notebookSize' : IDL.Text,
    'penBrand' : IDL.Text,
  });
  const PackType = IDL.Variant({
    'Strip' : IDL.Null,
    'Bottle' : IDL.Null,
    'Tablet' : IDL.Null,
    'Other' : IDL.Null,
  });
  const MedicalFields = IDL.Record({
    'packType' : PackType,
    'expiryDate' : IDL.Text,
    'company' : IDL.Text,
    'batchNo' : IDL.Text,
    'composition' : IDL.Text,
    'isControlled' : IDL.Bool,
  });
  const ElectricalFields = IDL.Record({
    'model' : IDL.Text,
    'isiCertified' : IDL.Bool,
    'lengthUnit' : IDL.Text,
    'wattage' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'color' : IDL.Text,
    'voltageRating' : IDL.Text,
    'wireGauge' : IDL.Text,
    'itemCategory' : IDL.Text,
    'batchNumber' : IDL.Text,
    'brand' : IDL.Text,
    'ampereRating' : IDL.Text,
  });
  const RestaurantCategory = IDL.Variant({
    'Veg' : IDL.Null,
    'NonVeg' : IDL.Null,
    'Vegan' : IDL.Null,
  });
  const RestaurantFields = IDL.Record({
    'expiryDate' : IDL.Opt(IDL.Text),
    'category' : RestaurantCategory,
  });
  const FruitsVegetablesFields = IDL.Record({
    'unit' : IDL.Text,
    'freshnessDate' : IDL.Opt(IDL.Text),
    'originSource' : IDL.Text,
    'productType' : IDL.Text,
    'seasonalTag' : IDL.Text,
    'batchNumber' : IDL.Opt(IDL.Text),
    'variety' : IDL.Text,
  });
  const ElectronicsFields = IDL.Record({
    'model' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'serialNo' : IDL.Text,
    'warrantyMonths' : IDL.Nat,
    'brand' : IDL.Text,
  });
  const MobileFields = IDL.Record({
    'ram' : IDL.Text,
    'mobileCategory' : IDL.Text,
    'model' : IDL.Text,
    'displaySize' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'storage' : IDL.Text,
    'imei' : IDL.Text,
    'color' : IDL.Text,
    'compatibility' : IDL.Text,
    'accessoryType' : IDL.Text,
    'serialNumber' : IDL.Text,
    'warrantyMonths' : IDL.Nat,
    'brand' : IDL.Text,
    'processor' : IDL.Text,
  });
  const ClothingFields = IDL.Record({
    'expiryDate' : IDL.Opt(IDL.Text),
    'color' : IDL.Text,
    'size' : IDL.Text,
    'itemName' : IDL.Text,
    'brand' : IDL.Text,
  });
  const EngineFields = IDL.Variant({
    'Salon' : SalonFields,
    'Footwear' : FootwearFields,
    'Jewelry' : JewelryFields,
    'AutoParts' : AutoPartsFields,
    'Grocery' : GroceryFields,
    'AgroProducts' : AgroProductsFields,
    'Hardware' : HardwareFields,
    'General' : GeneralFields,
    'BuildingMaterial' : BuildingMaterialFields,
    'Stationery' : StationeryFields,
    'Medical' : MedicalFields,
    'Electrical' : ElectricalFields,
    'Restaurant' : RestaurantFields,
    'FruitsVegetables' : FruitsVegetablesFields,
    'Electronics' : ElectronicsFields,
    'Mobile' : MobileFields,
    'Clothing' : ClothingFields,
  });
  const CreateProductInput = IDL.Record({
    'retailPrice' : IDL.Float64,
    'shopId' : IDL.Text,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Float64,
    'unit' : IDL.Text,
    'isActive' : IDL.Bool,
    'minStock' : IDL.Float64,
    'stock' : IDL.Float64,
    'labourCost' : IDL.Opt(IDL.Float64),
    'barcode' : IDL.Opt(IDL.Text),
    'shopType' : ShopType,
    'category' : IDL.Text,
    'transportCost' : IDL.Opt(IDL.Float64),
    'costPrice' : IDL.Float64,
    'engineFields' : EngineFields,
  });
  const ProductView = IDL.Record({
    'id' : ProductId,
    'retailPrice' : IDL.Float64,
    'shopId' : IDL.Text,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Float64,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'lastSaleTime' : IDL.Opt(Timestamp),
    'isActive' : IDL.Bool,
    'minStock' : IDL.Float64,
    'updatedAt' : Timestamp,
    'stock' : IDL.Float64,
    'labourCost' : IDL.Opt(IDL.Float64),
    'barcode' : IDL.Opt(IDL.Text),
    'shopType' : ShopType,
    'category' : IDL.Text,
    'transportCost' : IDL.Opt(IDL.Float64),
    'costPrice' : IDL.Float64,
    'engineFields' : EngineFields,
  });
  const CreateReturnInput = IDL.Record({
    'customerName' : IDL.Text,
    'originalBillId' : BillId,
    'customerPhone' : IDL.Text,
    'returnItems' : IDL.Vec(ReturnItem),
  });
  const SupplierId = IDL.Text;
  const Supplier = IDL.Record({
    'id' : SupplierId,
    'shopId' : IDL.Text,
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'businessType' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'defaultTransportCharge' : IDL.Opt(IDL.Text),
  });
  const SupplierPurchaseId = IDL.Text;
  const SupplierPurchase = IDL.Record({
    'id' : SupplierPurchaseId,
    'purchasePrice' : IDL.Text,
    'shopId' : IDL.Text,
    'purchaseDate' : IDL.Int,
    'productId' : IDL.Nat,
    'transportCharge' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'supplierId' : SupplierId,
  });
  const AdminNoteView = IDL.Record({
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'noteId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'targetPrincipal' : IDL.Text,
    'updatedAt' : IDL.Opt(IDL.Int),
  });
  const ShopAdminView = IDL.Record({
    'principal' : IDL.Text,
    'language' : IDL.Text,
    'currency' : IDL.Text,
    'shopName' : IDL.Text,
    'shopType' : IDL.Text,
    'taxSystem' : IDL.Text,
    'isDisabled' : IDL.Bool,
  });
  const UserView = IDL.Record({
    'firstSeen' : IDL.Int,
    'principal' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'isActive' : IDL.Bool,
    'loginCount' : IDL.Nat,
    'shopName' : IDL.Text,
    'shopType' : IDL.Text,
    'lastSeen' : IDL.Int,
  });
  const DeadStockProduct = IDL.Record({
    'name' : IDL.Text,
    'lastSaleTime' : IDL.Opt(Timestamp),
    'productId' : ProductId,
    'daysInactive' : IDL.Nat,
  });
  const SmartDefaultCharges = IDL.Record({
    'defaultOtherCharge' : IDL.Opt(IDL.Text),
    'defaultLabourCharge' : IDL.Opt(IDL.Text),
    'defaultTransportCharge' : IDL.Opt(IDL.Text),
  });
  const SupplierPurchaseWithName = IDL.Record({
    'supplierName' : IDL.Text,
    'purchase' : SupplierPurchase,
  });
  const LowStockProduct = IDL.Record({
    'name' : IDL.Text,
    'productId' : ProductId,
    'minStock' : IDL.Float64,
    'stock' : IDL.Float64,
  });
  const MetalRates = IDL.Record({
    'isStale' : IDL.Bool,
    'lastUpdated' : IDL.Int,
    'available' : IDL.Bool,
    'gold22k' : IDL.Float64,
    'gold24k' : IDL.Float64,
    'silver' : IDL.Float64,
  });
  const ShopRole = IDL.Variant({ 'owner' : IDL.Null, 'staff' : IDL.Null });
  const NearExpiryProduct = IDL.Record({
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'productId' : ProductId,
    'daysLeft' : IDL.Int,
  });
  const PublicBillView = IDL.Record({
    'id' : BillId,
    'customerName' : IDL.Text,
    'status' : BillStatus,
    'customerPhone' : IDL.Text,
    'createdAt' : Timestamp,
    'grandTotal' : IDL.Float64,
    'billNumber' : IDL.Nat,
    'taxBreakdown' : TaxBreakdown,
    'extraCharges' : IDL.Vec(ExtraCharge),
    'items' : IDL.Vec(BillItem),
    'priceType' : PriceType,
    'totalDiscount' : IDL.Float64,
    'taxSystem' : TaxSystem,
    'taxRate' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const AnalyticsPeriod = IDL.Variant({
    'Week' : IDL.Null,
    'Month' : IDL.Null,
    'Today' : IDL.Null,
  });
  const SalesSummary = IDL.Record({
    'totalProfit' : IDL.Float64,
    'totalSales' : IDL.Float64,
    'billCount' : IDL.Nat,
  });
  const NumberFormat = IDL.Variant({
    'Indian' : IDL.Null,
    'International' : IDL.Null,
  });
  const Language = IDL.Variant({
    'BahasaIndonesia' : IDL.Null,
    'Swahili' : IDL.Null,
    'Urdu' : IDL.Null,
    'Portuguese' : IDL.Null,
    'Spanish' : IDL.Null,
    'Bengali' : IDL.Null,
    'Hindi' : IDL.Null,
    'English' : IDL.Null,
    'Arabic' : IDL.Null,
    'French' : IDL.Null,
  });
  const DateFormat = IDL.Variant({
    'MMDDYYYY' : IDL.Null,
    'DDMMYYYY' : IDL.Null,
  });
  const ShopConfig = IDL.Record({
    'isSetupComplete' : IDL.Bool,
    'numberFormat' : NumberFormat,
    'country' : IDL.Text,
    'shopPhone' : IDL.Text,
    'expiryAlertThresholdDays' : IDL.Nat,
    'minStockAlertEnabled' : IDL.Bool,
    'language' : Language,
    'dateFormat' : DateFormat,
    'vatNumber' : IDL.Opt(IDL.Text),
    'deadStockAlertDays' : IDL.Nat,
    'currency' : IDL.Text,
    'shopName' : IDL.Text,
    'shopType' : ShopType,
    'shopEmail' : IDL.Text,
    'taxSystem' : TaxSystem,
    'shopAddress' : IDL.Text,
    'taxRate' : IDL.Float64,
    'gstinNumber' : IDL.Opt(IDL.Text),
    'defaultCharges' : IDL.Opt(SmartDefaultCharges),
  });
  const CustomerView = IDL.Record({
    'id' : CustomerId,
    'shopId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastPurchaseDate' : IDL.Opt(IDL.Int),
    'totalSpent' : IDL.Float64,
    'totalBills' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const StaffMember = IDL.Record({
    'principal' : IDL.Principal,
    'role' : ShopRole,
    'addedAt' : IDL.Int,
  });
  const TopProduct = IDL.Record({
    'revenue' : IDL.Float64,
    'name' : IDL.Text,
    'productId' : ProductId,
    'totalQty' : IDL.Float64,
    'profit' : IDL.Float64,
  });
  const BillFilter = IDL.Record({
    'status' : IDL.Opt(BillStatus),
    'shopId' : IDL.Opt(IDL.Text),
    'searchCustomer' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
  });
  const ProductFilter = IDL.Record({
    'shopId' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'searchName' : IDL.Opt(IDL.Text),
    'shopType' : IDL.Opt(ShopType),
    'category' : IDL.Opt(IDL.Text),
  });
  const ReturnFilter = IDL.Record({
    'status' : IDL.Opt(ReturnStatus),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
  });
  const RejectReturnInput = IDL.Record({
    'returnBillId' : ReturnBillId,
    'reason' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateProductInput = IDL.Record({
    'id' : ProductId,
    'retailPrice' : IDL.Float64,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Float64,
    'unit' : IDL.Text,
    'isActive' : IDL.Bool,
    'minStock' : IDL.Float64,
    'stock' : IDL.Float64,
    'labourCost' : IDL.Opt(IDL.Float64),
    'barcode' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'transportCost' : IDL.Opt(IDL.Float64),
    'costPrice' : IDL.Float64,
    'engineFields' : EngineFields,
  });
  
  return IDL.Service({
    'addAdminNote' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addStaff' : IDL.Func([IDL.Text, IDL.Principal], [Result], []),
    'adminBlockUser' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteShop' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'applyStoreCredit' : IDL.Func(
        [IDL.Text, ApplyStoreCreditInput],
        [CustomerCredit],
        [],
      ),
    'approveReturn' : IDL.Func([IDL.Text, ReturnBillId], [ReturnBill], []),
    'cancelBill' : IDL.Func([BillId], [IDL.Bool], []),
    'createBill' : IDL.Func([IDL.Text, CreateBillInput], [Bill], []),
    'createOrUpdateCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [CustomerId],
        [],
      ),
    'createProduct' : IDL.Func([CreateProductInput], [ProductView], []),
    'createReturn' : IDL.Func([IDL.Text, CreateReturnInput], [ReturnBill], []),
    'createSupplier' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Supplier],
        [],
      ),
    'createSupplierPurchase' : IDL.Func(
        [
          IDL.Text,
          SupplierId,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [SupplierPurchase],
        [],
      ),
    'deleteAdminNote' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
    'generateBillShareToken' : IDL.Func([BillId], [IDL.Opt(IDL.Text)], []),
    'getAdminNotes' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(AdminNoteView), 'err' : IDL.Text })],
        [],
      ),
    'getAllShops' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ShopAdminView), 'err' : IDL.Text })],
        [],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(UserView), 'err' : IDL.Text })],
        [],
      ),
    'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
    'getCustomerBills' : IDL.Func(
        [IDL.Text, CustomerId],
        [IDL.Vec(Bill)],
        ['query'],
      ),
    'getCustomerCredit' : IDL.Func([IDL.Text, IDL.Text], [CustomerCredit], []),
    'getDeadStockProducts' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(DeadStockProduct)],
        ['query'],
      ),
    'getDefaultCharges' : IDL.Func(
        [],
        [IDL.Opt(SmartDefaultCharges)],
        ['query'],
      ),
    'getLastNPurchasesForProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(SupplierPurchaseWithName)],
        ['query'],
      ),
    'getLowStockProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LowStockProduct)],
        ['query'],
      ),
    'getMetalRates' : IDL.Func([], [MetalRates], ['query']),
    'getMyRole' : IDL.Func([IDL.Text], [ShopRole], []),
    'getNearExpiryProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NearExpiryProduct)],
        ['query'],
      ),
    'getNearExpiryProductsByDays' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(NearExpiryProduct)],
        ['query'],
      ),
    'getPendingPaymentBills' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], []),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductView)], ['query']),
    'getProductByBarcode' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ProductView)],
        ['query'],
      ),
    'getPublicBill' : IDL.Func(
        [BillId, IDL.Text],
        [IDL.Opt(PublicBillView)],
        ['query'],
      ),
    'getReturnsByBill' : IDL.Func(
        [IDL.Text, BillId],
        [IDL.Vec(ReturnBill)],
        [],
      ),
    'getSalesSummary' : IDL.Func(
        [IDL.Text, AnalyticsPeriod],
        [SalesSummary],
        [],
      ),
    'getShopConfig' : IDL.Func([], [IDL.Opt(ShopConfig)], ['query']),
    'getShopCustomers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomerView)],
        ['query'],
      ),
    'getShopStaff' : IDL.Func([IDL.Text], [IDL.Vec(StaffMember)], []),
    'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
    'getTopProducts' : IDL.Func(
        [IDL.Text, AnalyticsPeriod, IDL.Nat],
        [IDL.Vec(TopProduct)],
        [],
      ),
    'getUserDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserView, 'err' : IDL.Text })],
        [],
      ),
    'initAdmin' : IDL.Func([], [IDL.Bool], []),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'isSetupComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'listBills' : IDL.Func([IDL.Text, BillFilter], [IDL.Vec(Bill)], []),
    'listProducts' : IDL.Func(
        [ProductFilter],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'listPurchasesByProduct' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(SupplierPurchase)],
        ['query'],
      ),
    'listPurchasesBySupplier' : IDL.Func(
        [IDL.Text, SupplierId],
        [IDL.Vec(SupplierPurchase)],
        ['query'],
      ),
    'listReturns' : IDL.Func(
        [IDL.Text, ReturnFilter],
        [IDL.Vec(ReturnBill)],
        [],
      ),
    'listSuppliersByShop' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Supplier)],
        ['query'],
      ),
    'recordPayment' : IDL.Func([IDL.Text, BillId, IDL.Float64], [Bill], []),
    'recordReminderSent' : IDL.Func([IDL.Text, BillId], [], []),
    'recordUserLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'refreshMetalRates' : IDL.Func([], [], []),
    'rejectReturn' : IDL.Func([IDL.Text, RejectReturnInput], [ReturnBill], []),
    'removeStaff' : IDL.Func([IDL.Text, IDL.Principal], [Result], []),
    'saveShopConfig' : IDL.Func([ShopConfig], [ShopConfig], []),
    'searchCustomers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CustomerView)],
        ['query'],
      ),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'setDefaultCharges' : IDL.Func(
        [SmartDefaultCharges],
        [IDL.Opt(ShopConfig)],
        [],
      ),
    'setMetalRatesManual' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'setShopDisabled' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transformRatesResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProduct' : IDL.Func(
        [UpdateProductInput],
        [IDL.Opt(ProductView)],
        [],
      ),
    'updateShopConfig' : IDL.Func([ShopConfig], [IDL.Opt(ShopConfig)], []),
    'updateSupplier' : IDL.Func(
        [
          SupplierId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Opt(Supplier)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };