/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminNoteView {
  'isDeleted' : boolean,
  'content' : string,
  'noteId' : bigint,
  'createdAt' : bigint,
  'targetPrincipal' : string,
  'updatedAt' : [] | [bigint],
}
export interface AgroProductsFields {
  'weight' : number,
  'expiryDate' : [] | [string],
  'weightUnit' : string,
  'productType' : string,
  'batchNumber' : [] | [string],
  'brand' : string,
  'cropType' : string,
}
export type AnalyticsPeriod = { 'Week' : null } |
  { 'Month' : null } |
  { 'Today' : null };
export interface ApplyStoreCreditInput {
  'customerPhone' : string,
  'amount' : number,
  'billId' : BillId,
}
export interface AutoPartsFields {
  'vehicleBrand' : string,
  'expiryDate' : [] | [string],
  'partName' : string,
  'vehicleModel' : string,
  'partNo' : string,
}
export interface Bill {
  'id' : BillId,
  'customerName' : string,
  'status' : BillStatus,
  'customerPhone' : string,
  'createdAt' : Timestamp,
  'shareToken' : [] | [string],
  'amountPaid' : number,
  'grandTotal' : number,
  'billNumber' : bigint,
  'taxBreakdown' : TaxBreakdown,
  'paymentType' : PaymentType,
  'extraCharges' : Array<ExtraCharge>,
  'profit' : number,
  'amountPending' : number,
  'items' : Array<BillItem>,
  'priceType' : PriceType,
  'staffCreatedBy' : [] | [Principal],
  'totalDiscount' : number,
  'lastReminderSent' : [] | [Timestamp],
  'taxSystem' : TaxSystem,
  'taxRate' : number,
  'subtotal' : number,
}
export interface BillFilter {
  'status' : [] | [BillStatus],
  'searchCustomer' : [] | [string],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
}
export type BillId = bigint;
export interface BillItem {
  'qty' : number,
  'name' : string,
  'rate' : number,
  'unit' : string,
  'lineTotal' : number,
  'productId' : ProductId,
  'taxAmt' : number,
  'discount' : number,
}
export type BillStatus = { 'Saved' : null } |
  { 'Draft' : null } |
  { 'Cancelled' : null };
export interface BuildingMaterialFields {
  'weight' : string,
  'material_type' : string,
  'expiryDate' : [] | [string],
  'color' : string,
  'grade' : string,
  'size_dimensions' : string,
  'brand' : string,
}
export interface ClothingFields {
  'expiryDate' : [] | [string],
  'color' : string,
  'size' : string,
  'itemName' : string,
  'brand' : string,
}
export interface CreateBillInput {
  'customerName' : string,
  'customerPhone' : string,
  'amountPaid' : number,
  'billDiscount' : number,
  'paymentType' : PaymentType,
  'extraCharges' : Array<ExtraCharge>,
  'items' : Array<BillItem>,
  'priceType' : PriceType,
  'staffCreatedBy' : [] | [Principal],
}
export interface CreateProductInput {
  'retailPrice' : number,
  'shopId' : string,
  'name' : string,
  'wholesalePrice' : number,
  'unit' : string,
  'isActive' : boolean,
  'minStock' : number,
  'stock' : number,
  'labourCost' : [] | [number],
  'barcode' : [] | [string],
  'shopType' : ShopType,
  'category' : string,
  'transportCost' : [] | [number],
  'costPrice' : number,
  'engineFields' : EngineFields,
}
export interface CreateReturnInput {
  'customerName' : string,
  'originalBillId' : BillId,
  'customerPhone' : string,
  'returnItems' : Array<ReturnItem>,
}
export interface CreditTransaction {
  'id' : CreditTransactionId,
  'returnBillId' : [] | [ReturnBillId],
  'date' : Timestamp,
  'note' : string,
  'txType' : CreditTransactionType,
  'amount' : number,
  'billId' : [] | [BillId],
}
export type CreditTransactionId = bigint;
export type CreditTransactionType = { 'Used' : null } |
  { 'Earned' : null };
export interface CustomerCredit {
  'balance' : number,
  'shopId' : string,
  'customerId' : string,
  'transactions' : Array<CreditTransaction>,
}
export type CustomerId = bigint;
export interface CustomerView {
  'id' : CustomerId,
  'shopId' : string,
  'name' : string,
  'createdAt' : bigint,
  'lastPurchaseDate' : [] | [bigint],
  'totalSpent' : number,
  'totalBills' : bigint,
  'phone' : string,
}
export type DateFormat = { 'MMDDYYYY' : null } |
  { 'DDMMYYYY' : null };
export interface DeadStockProduct {
  'name' : string,
  'lastSaleTime' : [] | [Timestamp],
  'productId' : ProductId,
  'daysInactive' : bigint,
}
export interface ElectricalFields {
  'model' : string,
  'isiCertified' : boolean,
  'lengthUnit' : string,
  'wattage' : string,
  'expiryDate' : [] | [string],
  'color' : string,
  'voltageRating' : string,
  'wireGauge' : string,
  'itemCategory' : string,
  'batchNumber' : string,
  'brand' : string,
  'ampereRating' : string,
}
export interface ElectronicsFields {
  'model' : string,
  'expiryDate' : [] | [string],
  'serialNo' : string,
  'warrantyMonths' : bigint,
  'brand' : string,
}
export type EngineFields = { 'Salon' : SalonFields } |
  { 'Footwear' : FootwearFields } |
  { 'Jewelry' : JewelryFields } |
  { 'AutoParts' : AutoPartsFields } |
  { 'Grocery' : GroceryFields } |
  { 'AgroProducts' : AgroProductsFields } |
  { 'Hardware' : HardwareFields } |
  { 'General' : GeneralFields } |
  { 'BuildingMaterial' : BuildingMaterialFields } |
  { 'Stationery' : StationeryFields } |
  { 'Medical' : MedicalFields } |
  { 'Electrical' : ElectricalFields } |
  { 'Restaurant' : RestaurantFields } |
  { 'FruitsVegetables' : FruitsVegetablesFields } |
  { 'Electronics' : ElectronicsFields } |
  { 'Mobile' : MobileFields } |
  { 'Clothing' : ClothingFields };
export interface ExtraCharge { 'description' : string, 'amount' : number }
export interface FootwearFields {
  'model' : string,
  'expiryDate' : [] | [string],
  'color' : string,
  'size' : string,
  'sizeSystem' : SizeSystem,
  'brand' : string,
}
export interface FruitsVegetablesFields {
  'unit' : string,
  'freshnessDate' : [] | [string],
  'originSource' : string,
  'productType' : string,
  'seasonalTag' : string,
  'batchNumber' : [] | [string],
  'variety' : string,
}
export interface GeneralFields { 'expiryDate' : [] | [string] }
export interface GroceryFields {
  'expiryDate' : [] | [string],
  'decimalQtyEnabled' : boolean,
}
export interface HardwareFields { 'sku' : string, 'expiryDate' : [] | [string] }
export interface JewelryFields {
  'metal' : Metal,
  'expiryDate' : [] | [string],
  'metalRate' : number,
  'purity' : string,
  'makingCharges' : number,
  'weightGrams' : number,
}
export type Language = { 'BahasaIndonesia' : null } |
  { 'Swahili' : null } |
  { 'Urdu' : null } |
  { 'Portuguese' : null } |
  { 'Spanish' : null } |
  { 'Bengali' : null } |
  { 'Hindi' : null } |
  { 'English' : null } |
  { 'Arabic' : null } |
  { 'French' : null };
export interface LowStockProduct {
  'name' : string,
  'productId' : ProductId,
  'minStock' : number,
  'stock' : number,
}
export interface MedicalFields {
  'packType' : PackType,
  'expiryDate' : string,
  'company' : string,
  'batchNo' : string,
  'composition' : string,
  'isControlled' : boolean,
}
export type Metal = { 'Gold' : null } |
  { 'Platinum' : null } |
  { 'Other' : null } |
  { 'Silver' : null };
export interface MetalRates {
  'isStale' : boolean,
  'lastUpdated' : bigint,
  'available' : boolean,
  'gold22k' : number,
  'gold24k' : number,
  'silver' : number,
}
export interface MobileFields {
  'ram' : string,
  'mobileCategory' : string,
  'model' : string,
  'displaySize' : string,
  'expiryDate' : [] | [string],
  'storage' : string,
  'imei' : string,
  'color' : string,
  'compatibility' : string,
  'accessoryType' : string,
  'serialNumber' : string,
  'warrantyMonths' : bigint,
  'brand' : string,
  'processor' : string,
}
export interface NearExpiryProduct {
  'expiryDate' : string,
  'name' : string,
  'productId' : ProductId,
  'daysLeft' : bigint,
}
export type NumberFormat = { 'Indian' : null } |
  { 'International' : null };
export type PackType = { 'Strip' : null } |
  { 'Bottle' : null } |
  { 'Tablet' : null } |
  { 'Other' : null };
export type PaymentType = { 'full' : null } |
  { 'partial' : null };
export type PriceType = { 'Retail' : null } |
  { 'Custom' : null } |
  { 'Wholesale' : null };
export interface ProductFilter {
  'shopId' : [] | [string],
  'isActive' : [] | [boolean],
  'searchName' : [] | [string],
  'shopType' : [] | [ShopType],
  'category' : [] | [string],
}
export type ProductId = bigint;
export interface ProductView {
  'id' : ProductId,
  'retailPrice' : number,
  'shopId' : string,
  'name' : string,
  'wholesalePrice' : number,
  'createdAt' : Timestamp,
  'unit' : string,
  'lastSaleTime' : [] | [Timestamp],
  'isActive' : boolean,
  'minStock' : number,
  'updatedAt' : Timestamp,
  'stock' : number,
  'labourCost' : [] | [number],
  'barcode' : [] | [string],
  'shopType' : ShopType,
  'category' : string,
  'transportCost' : [] | [number],
  'costPrice' : number,
  'engineFields' : EngineFields,
}
export interface PublicBillView {
  'id' : BillId,
  'customerName' : string,
  'status' : BillStatus,
  'customerPhone' : string,
  'createdAt' : Timestamp,
  'grandTotal' : number,
  'billNumber' : bigint,
  'taxBreakdown' : TaxBreakdown,
  'extraCharges' : Array<ExtraCharge>,
  'items' : Array<BillItem>,
  'priceType' : PriceType,
  'totalDiscount' : number,
  'taxSystem' : TaxSystem,
  'taxRate' : number,
  'subtotal' : number,
}
export interface RejectReturnInput {
  'returnBillId' : ReturnBillId,
  'reason' : string,
}
export type RestaurantCategory = { 'Veg' : null } |
  { 'NonVeg' : null } |
  { 'Vegan' : null };
export interface RestaurantFields {
  'expiryDate' : [] | [string],
  'category' : RestaurantCategory,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface ReturnBill {
  'id' : ReturnBillId,
  'customerName' : string,
  'status' : ReturnStatus,
  'originalBillId' : BillId,
  'shopId' : string,
  'customerPhone' : string,
  'totalRefundAmount' : number,
  'approvedAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'rejectionReason' : [] | [string],
  'returnItems' : Array<ReturnItem>,
}
export type ReturnBillId = bigint;
export interface ReturnFilter {
  'status' : [] | [ReturnStatus],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
}
export interface ReturnItem {
  'returnQty' : number,
  'originalRate' : number,
  'name' : string,
  'lineTotal' : number,
  'productId' : ProductId,
  'reason' : [] | [string],
}
export type ReturnStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface SalesSummary {
  'totalProfit' : number,
  'totalSales' : number,
  'billCount' : bigint,
}
export interface SalonFields {
  'duration' : bigint,
  'staffName' : string,
  'expiryDate' : [] | [string],
}
export interface ShopAdminView {
  'principal' : string,
  'language' : string,
  'currency' : string,
  'shopName' : string,
  'shopType' : string,
  'taxSystem' : string,
  'isDisabled' : boolean,
}
export interface ShopConfig {
  'isSetupComplete' : boolean,
  'numberFormat' : NumberFormat,
  'country' : string,
  'shopPhone' : string,
  'expiryAlertThresholdDays' : bigint,
  'minStockAlertEnabled' : boolean,
  'language' : Language,
  'dateFormat' : DateFormat,
  'vatNumber' : [] | [string],
  'deadStockAlertDays' : bigint,
  'currency' : string,
  'shopName' : string,
  'shopType' : ShopType,
  'shopEmail' : string,
  'taxSystem' : TaxSystem,
  'shopAddress' : string,
  'taxRate' : number,
  'gstinNumber' : [] | [string],
  'defaultCharges' : [] | [SmartDefaultCharges],
}
export type ShopRole = { 'owner' : null } |
  { 'staff' : null };
export type ShopType = { 'Salon' : null } |
  { 'Footwear' : null } |
  { 'Jewelry' : null } |
  { 'AutoParts' : null } |
  { 'Grocery' : null } |
  { 'AgroProducts' : null } |
  { 'Hardware' : null } |
  { 'General' : null } |
  { 'BuildingMaterial' : null } |
  { 'Stationery' : null } |
  { 'Medical' : null } |
  { 'Electrical' : null } |
  { 'Restaurant' : null } |
  { 'FruitsVegetables' : null } |
  { 'Electronics' : null } |
  { 'Mobile' : null } |
  { 'Clothing' : null };
export type SizeSystem = { 'EU' : null } |
  { 'UK' : null } |
  { 'US' : null };
export interface SmartDefaultCharges {
  'defaultOtherCharge' : [] | [string],
  'defaultLabourCharge' : [] | [string],
  'defaultTransportCharge' : [] | [string],
}
export interface StaffMember {
  'principal' : Principal,
  'role' : ShopRole,
  'addedAt' : bigint,
}
export interface StationeryFields {
  'bookSubject' : string,
  'subType' : StationerySubType,
  'bookClass' : string,
  'expiryDate' : [] | [string],
  'penColor' : string,
  'notebookPages' : bigint,
  'bookMedium' : string,
  'notebookSize' : string,
  'penBrand' : string,
}
export type StationerySubType = { 'Pen' : null } |
  { 'Book' : null } |
  { 'File' : null } |
  { 'Notebook' : null } |
  { 'Other' : null };
export interface Supplier {
  'id' : SupplierId,
  'shopId' : string,
  'city' : [] | [string],
  'name' : string,
  'businessType' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
  'defaultTransportCharge' : [] | [string],
}
export type SupplierId = string;
export interface SupplierPurchase {
  'id' : SupplierPurchaseId,
  'purchasePrice' : string,
  'shopId' : string,
  'purchaseDate' : bigint,
  'productId' : bigint,
  'transportCharge' : string,
  'notes' : [] | [string],
  'quantity' : number,
  'supplierId' : SupplierId,
}
export type SupplierPurchaseId = string;
export interface SupplierPurchaseWithName {
  'supplierName' : string,
  'purchase' : SupplierPurchase,
}
export interface TaxBreakdown {
  'cgst' : number,
  'igst' : number,
  'sgst' : number,
}
export type TaxSystem = { 'GST' : null } |
  { 'VAT' : null } |
  { 'Generic' : null } |
  { 'SalesTax' : null };
export type Timestamp = bigint;
export interface TopProduct {
  'revenue' : number,
  'name' : string,
  'productId' : ProductId,
  'totalQty' : number,
  'profit' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateProductInput {
  'id' : ProductId,
  'retailPrice' : number,
  'name' : string,
  'wholesalePrice' : number,
  'unit' : string,
  'isActive' : boolean,
  'minStock' : number,
  'stock' : number,
  'labourCost' : [] | [number],
  'barcode' : [] | [string],
  'category' : string,
  'transportCost' : [] | [number],
  'costPrice' : number,
  'engineFields' : EngineFields,
}
export interface UserView {
  'firstSeen' : bigint,
  'principal' : string,
  'isBlocked' : boolean,
  'isActive' : boolean,
  'loginCount' : bigint,
  'shopName' : string,
  'shopType' : string,
  'lastSeen' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addAdminNote' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addStaff' : ActorMethod<[string, Principal], Result>,
  'adminBlockUser' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteShop' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteUser' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'applyStoreCredit' : ActorMethod<
    [string, ApplyStoreCreditInput],
    CustomerCredit
  >,
  'approveReturn' : ActorMethod<[string, ReturnBillId], ReturnBill>,
  'cancelBill' : ActorMethod<[BillId], boolean>,
  'createBill' : ActorMethod<[CreateBillInput], Bill>,
  'createOrUpdateCustomer' : ActorMethod<[string, string, string], CustomerId>,
  'createProduct' : ActorMethod<[CreateProductInput], ProductView>,
  'createReturn' : ActorMethod<[string, CreateReturnInput], ReturnBill>,
  'createSupplier' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    Supplier
  >,
  'createSupplierPurchase' : ActorMethod<
    [string, SupplierId, bigint, number, string, string, [] | [string]],
    SupplierPurchase
  >,
  'deleteAdminNote' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteSupplier' : ActorMethod<[SupplierId], boolean>,
  'generateBillShareToken' : ActorMethod<[BillId], [] | [string]>,
  'getAdminNotes' : ActorMethod<
    [string],
    { 'ok' : Array<AdminNoteView> } |
      { 'err' : string }
  >,
  'getAllShops' : ActorMethod<
    [],
    { 'ok' : Array<ShopAdminView> } |
      { 'err' : string }
  >,
  'getAllUsers' : ActorMethod<
    [],
    { 'ok' : Array<UserView> } |
      { 'err' : string }
  >,
  'getBill' : ActorMethod<[BillId], [] | [Bill]>,
  'getCustomerBills' : ActorMethod<[string, CustomerId], Array<Bill>>,
  'getCustomerCredit' : ActorMethod<[string, string], CustomerCredit>,
  'getDeadStockProducts' : ActorMethod<
    [string, bigint],
    Array<DeadStockProduct>
  >,
  'getDefaultCharges' : ActorMethod<[], [] | [SmartDefaultCharges]>,
  'getLastNPurchasesForProduct' : ActorMethod<
    [string, bigint, bigint],
    Array<SupplierPurchaseWithName>
  >,
  'getLowStockProducts' : ActorMethod<[string], Array<LowStockProduct>>,
  'getMetalRates' : ActorMethod<[], MetalRates>,
  'getMyRole' : ActorMethod<[string], ShopRole>,
  'getNearExpiryProducts' : ActorMethod<[string], Array<NearExpiryProduct>>,
  'getNearExpiryProductsByDays' : ActorMethod<
    [string, bigint],
    Array<NearExpiryProduct>
  >,
  'getPendingPaymentBills' : ActorMethod<[string], Array<Bill>>,
  'getProduct' : ActorMethod<[ProductId], [] | [ProductView]>,
  'getProductByBarcode' : ActorMethod<[string, string], [] | [ProductView]>,
  'getPublicBill' : ActorMethod<[BillId, string], [] | [PublicBillView]>,
  'getReturnsByBill' : ActorMethod<[string, BillId], Array<ReturnBill>>,
  'getSalesSummary' : ActorMethod<[AnalyticsPeriod], SalesSummary>,
  'getShopConfig' : ActorMethod<[], [] | [ShopConfig]>,
  'getShopCustomers' : ActorMethod<[string], Array<CustomerView>>,
  'getShopStaff' : ActorMethod<[string], Array<StaffMember>>,
  'getSupplier' : ActorMethod<[SupplierId], [] | [Supplier]>,
  'getTopProducts' : ActorMethod<[AnalyticsPeriod, bigint], Array<TopProduct>>,
  'getUserDetails' : ActorMethod<
    [string],
    { 'ok' : UserView } |
      { 'err' : string }
  >,
  'initAdmin' : ActorMethod<[], boolean>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'isSetupComplete' : ActorMethod<[], boolean>,
  'listBills' : ActorMethod<[BillFilter], Array<Bill>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<ProductView>>,
  'listPurchasesByProduct' : ActorMethod<
    [string, bigint],
    Array<SupplierPurchase>
  >,
  'listPurchasesBySupplier' : ActorMethod<
    [string, SupplierId],
    Array<SupplierPurchase>
  >,
  'listReturns' : ActorMethod<[string, ReturnFilter], Array<ReturnBill>>,
  'listSuppliersByShop' : ActorMethod<[string], Array<Supplier>>,
  'recordPayment' : ActorMethod<[string, BillId, number], Bill>,
  'recordReminderSent' : ActorMethod<[string, BillId], undefined>,
  'recordUserLogin' : ActorMethod<[string, string], undefined>,
  'refreshMetalRates' : ActorMethod<[], undefined>,
  'rejectReturn' : ActorMethod<[string, RejectReturnInput], ReturnBill>,
  'removeStaff' : ActorMethod<[string, Principal], Result>,
  'saveShopConfig' : ActorMethod<[ShopConfig], ShopConfig>,
  'searchCustomers' : ActorMethod<[string, string], Array<CustomerView>>,
  'searchProducts' : ActorMethod<[string, string], Array<ProductView>>,
  'setDefaultCharges' : ActorMethod<[SmartDefaultCharges], [] | [ShopConfig]>,
  'setMetalRatesManual' : ActorMethod<[number, number], undefined>,
  'setShopDisabled' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transformRatesResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'updateProduct' : ActorMethod<[UpdateProductInput], [] | [ProductView]>,
  'updateShopConfig' : ActorMethod<[ShopConfig], [] | [ShopConfig]>,
  'updateSupplier' : ActorMethod<
    [
      SupplierId,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    [] | [Supplier]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];